// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/msal4/hassah_school_server/ent/assignment"
	"github.com/msal4/hassah_school_server/ent/assignmentsubmission"
	"github.com/msal4/hassah_school_server/ent/predicate"
	"github.com/msal4/hassah_school_server/ent/user"
)

// AssignmentSubmissionUpdate is the builder for updating AssignmentSubmission entities.
type AssignmentSubmissionUpdate struct {
	config
	hooks    []Hook
	mutation *AssignmentSubmissionMutation
}

// Where appends a list predicates to the AssignmentSubmissionUpdate builder.
func (asu *AssignmentSubmissionUpdate) Where(ps ...predicate.AssignmentSubmission) *AssignmentSubmissionUpdate {
	asu.mutation.Where(ps...)
	return asu
}

// SetFiles sets the "files" field.
func (asu *AssignmentSubmissionUpdate) SetFiles(s []string) *AssignmentSubmissionUpdate {
	asu.mutation.SetFiles(s)
	return asu
}

// SetSubmittedAt sets the "submitted_at" field.
func (asu *AssignmentSubmissionUpdate) SetSubmittedAt(t time.Time) *AssignmentSubmissionUpdate {
	asu.mutation.SetSubmittedAt(t)
	return asu
}

// SetNillableSubmittedAt sets the "submitted_at" field if the given value is not nil.
func (asu *AssignmentSubmissionUpdate) SetNillableSubmittedAt(t *time.Time) *AssignmentSubmissionUpdate {
	if t != nil {
		asu.SetSubmittedAt(*t)
	}
	return asu
}

// ClearSubmittedAt clears the value of the "submitted_at" field.
func (asu *AssignmentSubmissionUpdate) ClearSubmittedAt() *AssignmentSubmissionUpdate {
	asu.mutation.ClearSubmittedAt()
	return asu
}

// SetStudentID sets the "student" edge to the User entity by ID.
func (asu *AssignmentSubmissionUpdate) SetStudentID(id uuid.UUID) *AssignmentSubmissionUpdate {
	asu.mutation.SetStudentID(id)
	return asu
}

// SetStudent sets the "student" edge to the User entity.
func (asu *AssignmentSubmissionUpdate) SetStudent(u *User) *AssignmentSubmissionUpdate {
	return asu.SetStudentID(u.ID)
}

// SetAssignmentID sets the "assignment" edge to the Assignment entity by ID.
func (asu *AssignmentSubmissionUpdate) SetAssignmentID(id uuid.UUID) *AssignmentSubmissionUpdate {
	asu.mutation.SetAssignmentID(id)
	return asu
}

// SetAssignment sets the "assignment" edge to the Assignment entity.
func (asu *AssignmentSubmissionUpdate) SetAssignment(a *Assignment) *AssignmentSubmissionUpdate {
	return asu.SetAssignmentID(a.ID)
}

// Mutation returns the AssignmentSubmissionMutation object of the builder.
func (asu *AssignmentSubmissionUpdate) Mutation() *AssignmentSubmissionMutation {
	return asu.mutation
}

// ClearStudent clears the "student" edge to the User entity.
func (asu *AssignmentSubmissionUpdate) ClearStudent() *AssignmentSubmissionUpdate {
	asu.mutation.ClearStudent()
	return asu
}

// ClearAssignment clears the "assignment" edge to the Assignment entity.
func (asu *AssignmentSubmissionUpdate) ClearAssignment() *AssignmentSubmissionUpdate {
	asu.mutation.ClearAssignment()
	return asu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (asu *AssignmentSubmissionUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	asu.defaults()
	if len(asu.hooks) == 0 {
		if err = asu.check(); err != nil {
			return 0, err
		}
		affected, err = asu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*AssignmentSubmissionMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = asu.check(); err != nil {
				return 0, err
			}
			asu.mutation = mutation
			affected, err = asu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(asu.hooks) - 1; i >= 0; i-- {
			if asu.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = asu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, asu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (asu *AssignmentSubmissionUpdate) SaveX(ctx context.Context) int {
	affected, err := asu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (asu *AssignmentSubmissionUpdate) Exec(ctx context.Context) error {
	_, err := asu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (asu *AssignmentSubmissionUpdate) ExecX(ctx context.Context) {
	if err := asu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (asu *AssignmentSubmissionUpdate) defaults() {
	if _, ok := asu.mutation.UpdatedAt(); !ok {
		v := assignmentsubmission.UpdateDefaultUpdatedAt()
		asu.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (asu *AssignmentSubmissionUpdate) check() error {
	if _, ok := asu.mutation.StudentID(); asu.mutation.StudentCleared() && !ok {
		return errors.New("ent: clearing a required unique edge \"student\"")
	}
	if _, ok := asu.mutation.AssignmentID(); asu.mutation.AssignmentCleared() && !ok {
		return errors.New("ent: clearing a required unique edge \"assignment\"")
	}
	return nil
}

func (asu *AssignmentSubmissionUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   assignmentsubmission.Table,
			Columns: assignmentsubmission.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: assignmentsubmission.FieldID,
			},
		},
	}
	if ps := asu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := asu.mutation.UpdatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: assignmentsubmission.FieldUpdatedAt,
		})
	}
	if value, ok := asu.mutation.Files(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeJSON,
			Value:  value,
			Column: assignmentsubmission.FieldFiles,
		})
	}
	if value, ok := asu.mutation.SubmittedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: assignmentsubmission.FieldSubmittedAt,
		})
	}
	if asu.mutation.SubmittedAtCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Column: assignmentsubmission.FieldSubmittedAt,
		})
	}
	if asu.mutation.StudentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   assignmentsubmission.StudentTable,
			Columns: []string{assignmentsubmission.StudentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: user.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := asu.mutation.StudentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   assignmentsubmission.StudentTable,
			Columns: []string{assignmentsubmission.StudentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if asu.mutation.AssignmentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   assignmentsubmission.AssignmentTable,
			Columns: []string{assignmentsubmission.AssignmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: assignment.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := asu.mutation.AssignmentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   assignmentsubmission.AssignmentTable,
			Columns: []string{assignmentsubmission.AssignmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: assignment.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, asu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{assignmentsubmission.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return 0, err
	}
	return n, nil
}

// AssignmentSubmissionUpdateOne is the builder for updating a single AssignmentSubmission entity.
type AssignmentSubmissionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AssignmentSubmissionMutation
}

// SetFiles sets the "files" field.
func (asuo *AssignmentSubmissionUpdateOne) SetFiles(s []string) *AssignmentSubmissionUpdateOne {
	asuo.mutation.SetFiles(s)
	return asuo
}

// SetSubmittedAt sets the "submitted_at" field.
func (asuo *AssignmentSubmissionUpdateOne) SetSubmittedAt(t time.Time) *AssignmentSubmissionUpdateOne {
	asuo.mutation.SetSubmittedAt(t)
	return asuo
}

// SetNillableSubmittedAt sets the "submitted_at" field if the given value is not nil.
func (asuo *AssignmentSubmissionUpdateOne) SetNillableSubmittedAt(t *time.Time) *AssignmentSubmissionUpdateOne {
	if t != nil {
		asuo.SetSubmittedAt(*t)
	}
	return asuo
}

// ClearSubmittedAt clears the value of the "submitted_at" field.
func (asuo *AssignmentSubmissionUpdateOne) ClearSubmittedAt() *AssignmentSubmissionUpdateOne {
	asuo.mutation.ClearSubmittedAt()
	return asuo
}

// SetStudentID sets the "student" edge to the User entity by ID.
func (asuo *AssignmentSubmissionUpdateOne) SetStudentID(id uuid.UUID) *AssignmentSubmissionUpdateOne {
	asuo.mutation.SetStudentID(id)
	return asuo
}

// SetStudent sets the "student" edge to the User entity.
func (asuo *AssignmentSubmissionUpdateOne) SetStudent(u *User) *AssignmentSubmissionUpdateOne {
	return asuo.SetStudentID(u.ID)
}

// SetAssignmentID sets the "assignment" edge to the Assignment entity by ID.
func (asuo *AssignmentSubmissionUpdateOne) SetAssignmentID(id uuid.UUID) *AssignmentSubmissionUpdateOne {
	asuo.mutation.SetAssignmentID(id)
	return asuo
}

// SetAssignment sets the "assignment" edge to the Assignment entity.
func (asuo *AssignmentSubmissionUpdateOne) SetAssignment(a *Assignment) *AssignmentSubmissionUpdateOne {
	return asuo.SetAssignmentID(a.ID)
}

// Mutation returns the AssignmentSubmissionMutation object of the builder.
func (asuo *AssignmentSubmissionUpdateOne) Mutation() *AssignmentSubmissionMutation {
	return asuo.mutation
}

// ClearStudent clears the "student" edge to the User entity.
func (asuo *AssignmentSubmissionUpdateOne) ClearStudent() *AssignmentSubmissionUpdateOne {
	asuo.mutation.ClearStudent()
	return asuo
}

// ClearAssignment clears the "assignment" edge to the Assignment entity.
func (asuo *AssignmentSubmissionUpdateOne) ClearAssignment() *AssignmentSubmissionUpdateOne {
	asuo.mutation.ClearAssignment()
	return asuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (asuo *AssignmentSubmissionUpdateOne) Select(field string, fields ...string) *AssignmentSubmissionUpdateOne {
	asuo.fields = append([]string{field}, fields...)
	return asuo
}

// Save executes the query and returns the updated AssignmentSubmission entity.
func (asuo *AssignmentSubmissionUpdateOne) Save(ctx context.Context) (*AssignmentSubmission, error) {
	var (
		err  error
		node *AssignmentSubmission
	)
	asuo.defaults()
	if len(asuo.hooks) == 0 {
		if err = asuo.check(); err != nil {
			return nil, err
		}
		node, err = asuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*AssignmentSubmissionMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = asuo.check(); err != nil {
				return nil, err
			}
			asuo.mutation = mutation
			node, err = asuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(asuo.hooks) - 1; i >= 0; i-- {
			if asuo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = asuo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, asuo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (asuo *AssignmentSubmissionUpdateOne) SaveX(ctx context.Context) *AssignmentSubmission {
	node, err := asuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (asuo *AssignmentSubmissionUpdateOne) Exec(ctx context.Context) error {
	_, err := asuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (asuo *AssignmentSubmissionUpdateOne) ExecX(ctx context.Context) {
	if err := asuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (asuo *AssignmentSubmissionUpdateOne) defaults() {
	if _, ok := asuo.mutation.UpdatedAt(); !ok {
		v := assignmentsubmission.UpdateDefaultUpdatedAt()
		asuo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (asuo *AssignmentSubmissionUpdateOne) check() error {
	if _, ok := asuo.mutation.StudentID(); asuo.mutation.StudentCleared() && !ok {
		return errors.New("ent: clearing a required unique edge \"student\"")
	}
	if _, ok := asuo.mutation.AssignmentID(); asuo.mutation.AssignmentCleared() && !ok {
		return errors.New("ent: clearing a required unique edge \"assignment\"")
	}
	return nil
}

func (asuo *AssignmentSubmissionUpdateOne) sqlSave(ctx context.Context) (_node *AssignmentSubmission, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   assignmentsubmission.Table,
			Columns: assignmentsubmission.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: assignmentsubmission.FieldID,
			},
		},
	}
	id, ok := asuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing AssignmentSubmission.ID for update")}
	}
	_spec.Node.ID.Value = id
	if fields := asuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, assignmentsubmission.FieldID)
		for _, f := range fields {
			if !assignmentsubmission.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != assignmentsubmission.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := asuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := asuo.mutation.UpdatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: assignmentsubmission.FieldUpdatedAt,
		})
	}
	if value, ok := asuo.mutation.Files(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeJSON,
			Value:  value,
			Column: assignmentsubmission.FieldFiles,
		})
	}
	if value, ok := asuo.mutation.SubmittedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: assignmentsubmission.FieldSubmittedAt,
		})
	}
	if asuo.mutation.SubmittedAtCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Column: assignmentsubmission.FieldSubmittedAt,
		})
	}
	if asuo.mutation.StudentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   assignmentsubmission.StudentTable,
			Columns: []string{assignmentsubmission.StudentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: user.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := asuo.mutation.StudentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   assignmentsubmission.StudentTable,
			Columns: []string{assignmentsubmission.StudentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if asuo.mutation.AssignmentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   assignmentsubmission.AssignmentTable,
			Columns: []string{assignmentsubmission.AssignmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: assignment.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := asuo.mutation.AssignmentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   assignmentsubmission.AssignmentTable,
			Columns: []string{assignmentsubmission.AssignmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: assignment.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &AssignmentSubmission{config: asuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, asuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{assignmentsubmission.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	return _node, nil
}
