// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/msal4/hassah_school_server/ent/assignment"
	"github.com/msal4/hassah_school_server/ent/assignmentsubmission"
	"github.com/msal4/hassah_school_server/ent/class"
	"github.com/msal4/hassah_school_server/ent/grade"
)

// AssignmentCreate is the builder for creating a Assignment entity.
type AssignmentCreate struct {
	config
	mutation *AssignmentMutation
	hooks    []Hook
}

// SetCreateTime sets the "create_time" field.
func (ac *AssignmentCreate) SetCreateTime(t time.Time) *AssignmentCreate {
	ac.mutation.SetCreateTime(t)
	return ac
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (ac *AssignmentCreate) SetNillableCreateTime(t *time.Time) *AssignmentCreate {
	if t != nil {
		ac.SetCreateTime(*t)
	}
	return ac
}

// SetUpdateTime sets the "update_time" field.
func (ac *AssignmentCreate) SetUpdateTime(t time.Time) *AssignmentCreate {
	ac.mutation.SetUpdateTime(t)
	return ac
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (ac *AssignmentCreate) SetNillableUpdateTime(t *time.Time) *AssignmentCreate {
	if t != nil {
		ac.SetUpdateTime(*t)
	}
	return ac
}

// SetName sets the "name" field.
func (ac *AssignmentCreate) SetName(s string) *AssignmentCreate {
	ac.mutation.SetName(s)
	return ac
}

// SetDescription sets the "description" field.
func (ac *AssignmentCreate) SetDescription(s string) *AssignmentCreate {
	ac.mutation.SetDescription(s)
	return ac
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (ac *AssignmentCreate) SetNillableDescription(s *string) *AssignmentCreate {
	if s != nil {
		ac.SetDescription(*s)
	}
	return ac
}

// SetIsExam sets the "is_exam" field.
func (ac *AssignmentCreate) SetIsExam(b bool) *AssignmentCreate {
	ac.mutation.SetIsExam(b)
	return ac
}

// SetNillableIsExam sets the "is_exam" field if the given value is not nil.
func (ac *AssignmentCreate) SetNillableIsExam(b *bool) *AssignmentCreate {
	if b != nil {
		ac.SetIsExam(*b)
	}
	return ac
}

// SetDueDate sets the "due_date" field.
func (ac *AssignmentCreate) SetDueDate(t time.Time) *AssignmentCreate {
	ac.mutation.SetDueDate(t)
	return ac
}

// SetDuration sets the "duration" field.
func (ac *AssignmentCreate) SetDuration(i int) *AssignmentCreate {
	ac.mutation.SetDuration(i)
	return ac
}

// SetNillableDuration sets the "duration" field if the given value is not nil.
func (ac *AssignmentCreate) SetNillableDuration(i *int) *AssignmentCreate {
	if i != nil {
		ac.SetDuration(*i)
	}
	return ac
}

// SetDeletedAt sets the "deleted_at" field.
func (ac *AssignmentCreate) SetDeletedAt(t time.Time) *AssignmentCreate {
	ac.mutation.SetDeletedAt(t)
	return ac
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (ac *AssignmentCreate) SetNillableDeletedAt(t *time.Time) *AssignmentCreate {
	if t != nil {
		ac.SetDeletedAt(*t)
	}
	return ac
}

// SetClassID sets the "class" edge to the Class entity by ID.
func (ac *AssignmentCreate) SetClassID(id int) *AssignmentCreate {
	ac.mutation.SetClassID(id)
	return ac
}

// SetClass sets the "class" edge to the Class entity.
func (ac *AssignmentCreate) SetClass(c *Class) *AssignmentCreate {
	return ac.SetClassID(c.ID)
}

// AddSubmissionIDs adds the "submissions" edge to the AssignmentSubmission entity by IDs.
func (ac *AssignmentCreate) AddSubmissionIDs(ids ...int) *AssignmentCreate {
	ac.mutation.AddSubmissionIDs(ids...)
	return ac
}

// AddSubmissions adds the "submissions" edges to the AssignmentSubmission entity.
func (ac *AssignmentCreate) AddSubmissions(a ...*AssignmentSubmission) *AssignmentCreate {
	ids := make([]int, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return ac.AddSubmissionIDs(ids...)
}

// AddGradeIDs adds the "grades" edge to the Grade entity by IDs.
func (ac *AssignmentCreate) AddGradeIDs(ids ...int) *AssignmentCreate {
	ac.mutation.AddGradeIDs(ids...)
	return ac
}

// AddGrades adds the "grades" edges to the Grade entity.
func (ac *AssignmentCreate) AddGrades(g ...*Grade) *AssignmentCreate {
	ids := make([]int, len(g))
	for i := range g {
		ids[i] = g[i].ID
	}
	return ac.AddGradeIDs(ids...)
}

// Mutation returns the AssignmentMutation object of the builder.
func (ac *AssignmentCreate) Mutation() *AssignmentMutation {
	return ac.mutation
}

// Save creates the Assignment in the database.
func (ac *AssignmentCreate) Save(ctx context.Context) (*Assignment, error) {
	var (
		err  error
		node *Assignment
	)
	ac.defaults()
	if len(ac.hooks) == 0 {
		if err = ac.check(); err != nil {
			return nil, err
		}
		node, err = ac.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*AssignmentMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = ac.check(); err != nil {
				return nil, err
			}
			ac.mutation = mutation
			if node, err = ac.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(ac.hooks) - 1; i >= 0; i-- {
			if ac.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = ac.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ac.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (ac *AssignmentCreate) SaveX(ctx context.Context) *Assignment {
	v, err := ac.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ac *AssignmentCreate) Exec(ctx context.Context) error {
	_, err := ac.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ac *AssignmentCreate) ExecX(ctx context.Context) {
	if err := ac.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ac *AssignmentCreate) defaults() {
	if _, ok := ac.mutation.CreateTime(); !ok {
		v := assignment.DefaultCreateTime()
		ac.mutation.SetCreateTime(v)
	}
	if _, ok := ac.mutation.UpdateTime(); !ok {
		v := assignment.DefaultUpdateTime()
		ac.mutation.SetUpdateTime(v)
	}
	if _, ok := ac.mutation.IsExam(); !ok {
		v := assignment.DefaultIsExam
		ac.mutation.SetIsExam(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ac *AssignmentCreate) check() error {
	if _, ok := ac.mutation.CreateTime(); !ok {
		return &ValidationError{Name: "create_time", err: errors.New(`ent: missing required field "create_time"`)}
	}
	if _, ok := ac.mutation.UpdateTime(); !ok {
		return &ValidationError{Name: "update_time", err: errors.New(`ent: missing required field "update_time"`)}
	}
	if _, ok := ac.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "name"`)}
	}
	if v, ok := ac.mutation.Name(); ok {
		if err := assignment.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "name": %w`, err)}
		}
	}
	if _, ok := ac.mutation.IsExam(); !ok {
		return &ValidationError{Name: "is_exam", err: errors.New(`ent: missing required field "is_exam"`)}
	}
	if _, ok := ac.mutation.DueDate(); !ok {
		return &ValidationError{Name: "due_date", err: errors.New(`ent: missing required field "due_date"`)}
	}
	if _, ok := ac.mutation.ClassID(); !ok {
		return &ValidationError{Name: "class", err: errors.New("ent: missing required edge \"class\"")}
	}
	return nil
}

func (ac *AssignmentCreate) sqlSave(ctx context.Context) (*Assignment, error) {
	_node, _spec := ac.createSpec()
	if err := sqlgraph.CreateNode(ctx, ac.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (ac *AssignmentCreate) createSpec() (*Assignment, *sqlgraph.CreateSpec) {
	var (
		_node = &Assignment{config: ac.config}
		_spec = &sqlgraph.CreateSpec{
			Table: assignment.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: assignment.FieldID,
			},
		}
	)
	if value, ok := ac.mutation.CreateTime(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: assignment.FieldCreateTime,
		})
		_node.CreateTime = value
	}
	if value, ok := ac.mutation.UpdateTime(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: assignment.FieldUpdateTime,
		})
		_node.UpdateTime = value
	}
	if value, ok := ac.mutation.Name(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: assignment.FieldName,
		})
		_node.Name = value
	}
	if value, ok := ac.mutation.Description(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: assignment.FieldDescription,
		})
		_node.Description = value
	}
	if value, ok := ac.mutation.IsExam(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeBool,
			Value:  value,
			Column: assignment.FieldIsExam,
		})
		_node.IsExam = value
	}
	if value, ok := ac.mutation.DueDate(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: assignment.FieldDueDate,
		})
		_node.DueDate = value
	}
	if value, ok := ac.mutation.Duration(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: assignment.FieldDuration,
		})
		_node.Duration = value
	}
	if value, ok := ac.mutation.DeletedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: assignment.FieldDeletedAt,
		})
		_node.DeletedAt = &value
	}
	if nodes := ac.mutation.ClassIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   assignment.ClassTable,
			Columns: []string{assignment.ClassColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: class.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.class_assignments = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := ac.mutation.SubmissionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   assignment.SubmissionsTable,
			Columns: []string{assignment.SubmissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: assignmentsubmission.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := ac.mutation.GradesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   assignment.GradesTable,
			Columns: []string{assignment.GradesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: grade.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// AssignmentCreateBulk is the builder for creating many Assignment entities in bulk.
type AssignmentCreateBulk struct {
	config
	builders []*AssignmentCreate
}

// Save creates the Assignment entities in the database.
func (acb *AssignmentCreateBulk) Save(ctx context.Context) ([]*Assignment, error) {
	specs := make([]*sqlgraph.CreateSpec, len(acb.builders))
	nodes := make([]*Assignment, len(acb.builders))
	mutators := make([]Mutator, len(acb.builders))
	for i := range acb.builders {
		func(i int, root context.Context) {
			builder := acb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AssignmentMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, acb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, acb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{err.Error(), err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, acb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (acb *AssignmentCreateBulk) SaveX(ctx context.Context) []*Assignment {
	v, err := acb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (acb *AssignmentCreateBulk) Exec(ctx context.Context) error {
	_, err := acb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (acb *AssignmentCreateBulk) ExecX(ctx context.Context) {
	if err := acb.Exec(ctx); err != nil {
		panic(err)
	}
}
