// Code generated by entc, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/msal4/hassah_school_server/ent/assignment"
	"github.com/msal4/hassah_school_server/ent/assignmentsubmission"
	"github.com/msal4/hassah_school_server/ent/attendance"
	"github.com/msal4/hassah_school_server/ent/class"
	"github.com/msal4/hassah_school_server/ent/grade"
	"github.com/msal4/hassah_school_server/ent/group"
	"github.com/msal4/hassah_school_server/ent/message"
	"github.com/msal4/hassah_school_server/ent/schedule"
	"github.com/msal4/hassah_school_server/ent/schema"
	"github.com/msal4/hassah_school_server/ent/school"
	"github.com/msal4/hassah_school_server/ent/stage"
	"github.com/msal4/hassah_school_server/ent/timemixin"
	"github.com/msal4/hassah_school_server/ent/tuitionpayment"
	"github.com/msal4/hassah_school_server/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	assignmentMixin := schema.Assignment{}.Mixin()
	assignmentMixinFields0 := assignmentMixin[0].Fields()
	_ = assignmentMixinFields0
	assignmentFields := schema.Assignment{}.Fields()
	_ = assignmentFields
	// assignmentDescCreatedAt is the schema descriptor for created_at field.
	assignmentDescCreatedAt := assignmentMixinFields0[0].Descriptor()
	// assignment.DefaultCreatedAt holds the default value on creation for the created_at field.
	assignment.DefaultCreatedAt = assignmentDescCreatedAt.Default.(func() time.Time)
	// assignmentDescUpdatedAt is the schema descriptor for updated_at field.
	assignmentDescUpdatedAt := assignmentMixinFields0[1].Descriptor()
	// assignment.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	assignment.DefaultUpdatedAt = assignmentDescUpdatedAt.Default.(func() time.Time)
	// assignment.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	assignment.UpdateDefaultUpdatedAt = assignmentDescUpdatedAt.UpdateDefault.(func() time.Time)
	// assignmentDescName is the schema descriptor for name field.
	assignmentDescName := assignmentFields[0].Descriptor()
	// assignment.NameValidator is a validator for the "name" field. It is called by the builders before save.
	assignment.NameValidator = assignmentDescName.Validators[0].(func(string) error)
	// assignmentDescIsExam is the schema descriptor for is_exam field.
	assignmentDescIsExam := assignmentFields[2].Descriptor()
	// assignment.DefaultIsExam holds the default value on creation for the is_exam field.
	assignment.DefaultIsExam = assignmentDescIsExam.Default.(bool)
	assignmentsubmissionMixin := schema.AssignmentSubmission{}.Mixin()
	assignmentsubmissionMixinFields0 := assignmentsubmissionMixin[0].Fields()
	_ = assignmentsubmissionMixinFields0
	assignmentsubmissionFields := schema.AssignmentSubmission{}.Fields()
	_ = assignmentsubmissionFields
	// assignmentsubmissionDescCreatedAt is the schema descriptor for created_at field.
	assignmentsubmissionDescCreatedAt := assignmentsubmissionMixinFields0[0].Descriptor()
	// assignmentsubmission.DefaultCreatedAt holds the default value on creation for the created_at field.
	assignmentsubmission.DefaultCreatedAt = assignmentsubmissionDescCreatedAt.Default.(func() time.Time)
	// assignmentsubmissionDescUpdatedAt is the schema descriptor for updated_at field.
	assignmentsubmissionDescUpdatedAt := assignmentsubmissionMixinFields0[1].Descriptor()
	// assignmentsubmission.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	assignmentsubmission.DefaultUpdatedAt = assignmentsubmissionDescUpdatedAt.Default.(func() time.Time)
	// assignmentsubmission.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	assignmentsubmission.UpdateDefaultUpdatedAt = assignmentsubmissionDescUpdatedAt.UpdateDefault.(func() time.Time)
	attendanceMixin := schema.Attendance{}.Mixin()
	attendanceMixinFields0 := attendanceMixin[0].Fields()
	_ = attendanceMixinFields0
	attendanceFields := schema.Attendance{}.Fields()
	_ = attendanceFields
	// attendanceDescCreatedAt is the schema descriptor for created_at field.
	attendanceDescCreatedAt := attendanceMixinFields0[0].Descriptor()
	// attendance.DefaultCreatedAt holds the default value on creation for the created_at field.
	attendance.DefaultCreatedAt = attendanceDescCreatedAt.Default.(func() time.Time)
	// attendanceDescUpdatedAt is the schema descriptor for updated_at field.
	attendanceDescUpdatedAt := attendanceMixinFields0[1].Descriptor()
	// attendance.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	attendance.DefaultUpdatedAt = attendanceDescUpdatedAt.Default.(func() time.Time)
	// attendance.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	attendance.UpdateDefaultUpdatedAt = attendanceDescUpdatedAt.UpdateDefault.(func() time.Time)
	classMixin := schema.Class{}.Mixin()
	classMixinFields0 := classMixin[0].Fields()
	_ = classMixinFields0
	classFields := schema.Class{}.Fields()
	_ = classFields
	// classDescCreatedAt is the schema descriptor for created_at field.
	classDescCreatedAt := classMixinFields0[0].Descriptor()
	// class.DefaultCreatedAt holds the default value on creation for the created_at field.
	class.DefaultCreatedAt = classDescCreatedAt.Default.(func() time.Time)
	// classDescUpdatedAt is the schema descriptor for updated_at field.
	classDescUpdatedAt := classMixinFields0[1].Descriptor()
	// class.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	class.DefaultUpdatedAt = classDescUpdatedAt.Default.(func() time.Time)
	// class.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	class.UpdateDefaultUpdatedAt = classDescUpdatedAt.UpdateDefault.(func() time.Time)
	// classDescName is the schema descriptor for name field.
	classDescName := classFields[0].Descriptor()
	// class.NameValidator is a validator for the "name" field. It is called by the builders before save.
	class.NameValidator = classDescName.Validators[0].(func(string) error)
	gradeMixin := schema.Grade{}.Mixin()
	gradeMixinFields0 := gradeMixin[0].Fields()
	_ = gradeMixinFields0
	gradeFields := schema.Grade{}.Fields()
	_ = gradeFields
	// gradeDescCreatedAt is the schema descriptor for created_at field.
	gradeDescCreatedAt := gradeMixinFields0[0].Descriptor()
	// grade.DefaultCreatedAt holds the default value on creation for the created_at field.
	grade.DefaultCreatedAt = gradeDescCreatedAt.Default.(func() time.Time)
	// gradeDescUpdatedAt is the schema descriptor for updated_at field.
	gradeDescUpdatedAt := gradeMixinFields0[1].Descriptor()
	// grade.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	grade.DefaultUpdatedAt = gradeDescUpdatedAt.Default.(func() time.Time)
	// grade.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	grade.UpdateDefaultUpdatedAt = gradeDescUpdatedAt.UpdateDefault.(func() time.Time)
	// gradeDescExamGrade is the schema descriptor for exam_grade field.
	gradeDescExamGrade := gradeFields[0].Descriptor()
	// grade.ExamGradeValidator is a validator for the "exam_grade" field. It is called by the builders before save.
	grade.ExamGradeValidator = gradeDescExamGrade.Validators[0].(func(float64) error)
	groupMixin := schema.Group{}.Mixin()
	groupMixinFields0 := groupMixin[0].Fields()
	_ = groupMixinFields0
	groupFields := schema.Group{}.Fields()
	_ = groupFields
	// groupDescCreatedAt is the schema descriptor for created_at field.
	groupDescCreatedAt := groupMixinFields0[0].Descriptor()
	// group.DefaultCreatedAt holds the default value on creation for the created_at field.
	group.DefaultCreatedAt = groupDescCreatedAt.Default.(func() time.Time)
	// groupDescUpdatedAt is the schema descriptor for updated_at field.
	groupDescUpdatedAt := groupMixinFields0[1].Descriptor()
	// group.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	group.DefaultUpdatedAt = groupDescUpdatedAt.Default.(func() time.Time)
	// group.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	group.UpdateDefaultUpdatedAt = groupDescUpdatedAt.UpdateDefault.(func() time.Time)
	messageMixin := schema.Message{}.Mixin()
	messageMixinFields0 := messageMixin[0].Fields()
	_ = messageMixinFields0
	messageFields := schema.Message{}.Fields()
	_ = messageFields
	// messageDescCreatedAt is the schema descriptor for created_at field.
	messageDescCreatedAt := messageMixinFields0[0].Descriptor()
	// message.DefaultCreatedAt holds the default value on creation for the created_at field.
	message.DefaultCreatedAt = messageDescCreatedAt.Default.(func() time.Time)
	// messageDescUpdatedAt is the schema descriptor for updated_at field.
	messageDescUpdatedAt := messageMixinFields0[1].Descriptor()
	// message.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	message.DefaultUpdatedAt = messageDescUpdatedAt.Default.(func() time.Time)
	// message.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	message.UpdateDefaultUpdatedAt = messageDescUpdatedAt.UpdateDefault.(func() time.Time)
	scheduleFields := schema.Schedule{}.Fields()
	_ = scheduleFields
	// scheduleDescWeekday is the schema descriptor for weekday field.
	scheduleDescWeekday := scheduleFields[0].Descriptor()
	// schedule.WeekdayValidator is a validator for the "weekday" field. It is called by the builders before save.
	schedule.WeekdayValidator = scheduleDescWeekday.Validators[0].(func(uint8) error)
	// scheduleDescDuration is the schema descriptor for duration field.
	scheduleDescDuration := scheduleFields[2].Descriptor()
	// schedule.DefaultDuration holds the default value on creation for the duration field.
	schedule.DefaultDuration = scheduleDescDuration.Default.(int)
	schoolMixin := schema.School{}.Mixin()
	schoolMixinFields0 := schoolMixin[0].Fields()
	_ = schoolMixinFields0
	schoolFields := schema.School{}.Fields()
	_ = schoolFields
	// schoolDescCreatedAt is the schema descriptor for created_at field.
	schoolDescCreatedAt := schoolMixinFields0[0].Descriptor()
	// school.DefaultCreatedAt holds the default value on creation for the created_at field.
	school.DefaultCreatedAt = schoolDescCreatedAt.Default.(func() time.Time)
	// schoolDescUpdatedAt is the schema descriptor for updated_at field.
	schoolDescUpdatedAt := schoolMixinFields0[1].Descriptor()
	// school.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	school.DefaultUpdatedAt = schoolDescUpdatedAt.Default.(func() time.Time)
	// school.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	school.UpdateDefaultUpdatedAt = schoolDescUpdatedAt.UpdateDefault.(func() time.Time)
	// schoolDescName is the schema descriptor for name field.
	schoolDescName := schoolFields[0].Descriptor()
	// school.NameValidator is a validator for the "name" field. It is called by the builders before save.
	school.NameValidator = schoolDescName.Validators[0].(func(string) error)
	// schoolDescImage is the schema descriptor for image field.
	schoolDescImage := schoolFields[1].Descriptor()
	// school.ImageValidator is a validator for the "image" field. It is called by the builders before save.
	school.ImageValidator = schoolDescImage.Validators[0].(func(string) error)
	stageMixin := schema.Stage{}.Mixin()
	stageMixinFields0 := stageMixin[0].Fields()
	_ = stageMixinFields0
	stageFields := schema.Stage{}.Fields()
	_ = stageFields
	// stageDescCreatedAt is the schema descriptor for created_at field.
	stageDescCreatedAt := stageMixinFields0[0].Descriptor()
	// stage.DefaultCreatedAt holds the default value on creation for the created_at field.
	stage.DefaultCreatedAt = stageDescCreatedAt.Default.(func() time.Time)
	// stageDescUpdatedAt is the schema descriptor for updated_at field.
	stageDescUpdatedAt := stageMixinFields0[1].Descriptor()
	// stage.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	stage.DefaultUpdatedAt = stageDescUpdatedAt.Default.(func() time.Time)
	// stage.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	stage.UpdateDefaultUpdatedAt = stageDescUpdatedAt.UpdateDefault.(func() time.Time)
	// stageDescName is the schema descriptor for name field.
	stageDescName := stageFields[0].Descriptor()
	// stage.NameValidator is a validator for the "name" field. It is called by the builders before save.
	stage.NameValidator = stageDescName.Validators[0].(func(string) error)
	timemixinFields := schema.TimeMixin{}.Fields()
	_ = timemixinFields
	// timemixinDescCreatedAt is the schema descriptor for created_at field.
	timemixinDescCreatedAt := timemixinFields[0].Descriptor()
	// timemixin.DefaultCreatedAt holds the default value on creation for the created_at field.
	timemixin.DefaultCreatedAt = timemixinDescCreatedAt.Default.(func() time.Time)
	// timemixinDescUpdatedAt is the schema descriptor for updated_at field.
	timemixinDescUpdatedAt := timemixinFields[1].Descriptor()
	// timemixin.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	timemixin.DefaultUpdatedAt = timemixinDescUpdatedAt.Default.(func() time.Time)
	// timemixin.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	timemixin.UpdateDefaultUpdatedAt = timemixinDescUpdatedAt.UpdateDefault.(func() time.Time)
	tuitionpaymentMixin := schema.TuitionPayment{}.Mixin()
	tuitionpaymentMixinFields0 := tuitionpaymentMixin[0].Fields()
	_ = tuitionpaymentMixinFields0
	tuitionpaymentFields := schema.TuitionPayment{}.Fields()
	_ = tuitionpaymentFields
	// tuitionpaymentDescCreatedAt is the schema descriptor for created_at field.
	tuitionpaymentDescCreatedAt := tuitionpaymentMixinFields0[0].Descriptor()
	// tuitionpayment.DefaultCreatedAt holds the default value on creation for the created_at field.
	tuitionpayment.DefaultCreatedAt = tuitionpaymentDescCreatedAt.Default.(func() time.Time)
	// tuitionpaymentDescUpdatedAt is the schema descriptor for updated_at field.
	tuitionpaymentDescUpdatedAt := tuitionpaymentMixinFields0[1].Descriptor()
	// tuitionpayment.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	tuitionpayment.DefaultUpdatedAt = tuitionpaymentDescUpdatedAt.Default.(func() time.Time)
	// tuitionpayment.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	tuitionpayment.UpdateDefaultUpdatedAt = tuitionpaymentDescUpdatedAt.UpdateDefault.(func() time.Time)
	userMixin := schema.User{}.Mixin()
	userMixinFields0 := userMixin[0].Fields()
	_ = userMixinFields0
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userMixinFields0[0].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userMixinFields0[1].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userDescName is the schema descriptor for name field.
	userDescName := userFields[0].Descriptor()
	// user.NameValidator is a validator for the "name" field. It is called by the builders before save.
	user.NameValidator = userDescName.Validators[0].(func(string) error)
	// userDescUsername is the schema descriptor for username field.
	userDescUsername := userFields[1].Descriptor()
	// user.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	user.UsernameValidator = userDescUsername.Validators[0].(func(string) error)
	// userDescPassword is the schema descriptor for password field.
	userDescPassword := userFields[2].Descriptor()
	// user.PasswordValidator is a validator for the "password" field. It is called by the builders before save.
	user.PasswordValidator = userDescPassword.Validators[0].(func(string) error)
	// userDescPhone is the schema descriptor for phone field.
	userDescPhone := userFields[3].Descriptor()
	// user.PhoneValidator is a validator for the "phone" field. It is called by the builders before save.
	user.PhoneValidator = userDescPhone.Validators[0].(func(string) error)
	// userDescTokenVersion is the schema descriptor for token_version field.
	userDescTokenVersion := userFields[5].Descriptor()
	// user.DefaultTokenVersion holds the default value on creation for the token_version field.
	user.DefaultTokenVersion = userDescTokenVersion.Default.(int)
}
