// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/msal4/hassah_school_server/ent/predicate"
	"github.com/msal4/hassah_school_server/ent/timemixin"
)

// TimeMixinQuery is the builder for querying TimeMixin entities.
type TimeMixinQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.TimeMixin
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the TimeMixinQuery builder.
func (tmq *TimeMixinQuery) Where(ps ...predicate.TimeMixin) *TimeMixinQuery {
	tmq.predicates = append(tmq.predicates, ps...)
	return tmq
}

// Limit adds a limit step to the query.
func (tmq *TimeMixinQuery) Limit(limit int) *TimeMixinQuery {
	tmq.limit = &limit
	return tmq
}

// Offset adds an offset step to the query.
func (tmq *TimeMixinQuery) Offset(offset int) *TimeMixinQuery {
	tmq.offset = &offset
	return tmq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (tmq *TimeMixinQuery) Unique(unique bool) *TimeMixinQuery {
	tmq.unique = &unique
	return tmq
}

// Order adds an order step to the query.
func (tmq *TimeMixinQuery) Order(o ...OrderFunc) *TimeMixinQuery {
	tmq.order = append(tmq.order, o...)
	return tmq
}

// First returns the first TimeMixin entity from the query.
// Returns a *NotFoundError when no TimeMixin was found.
func (tmq *TimeMixinQuery) First(ctx context.Context) (*TimeMixin, error) {
	nodes, err := tmq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{timemixin.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (tmq *TimeMixinQuery) FirstX(ctx context.Context) *TimeMixin {
	node, err := tmq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first TimeMixin ID from the query.
// Returns a *NotFoundError when no TimeMixin ID was found.
func (tmq *TimeMixinQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = tmq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{timemixin.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (tmq *TimeMixinQuery) FirstIDX(ctx context.Context) int {
	id, err := tmq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single TimeMixin entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when exactly one TimeMixin entity is not found.
// Returns a *NotFoundError when no TimeMixin entities are found.
func (tmq *TimeMixinQuery) Only(ctx context.Context) (*TimeMixin, error) {
	nodes, err := tmq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{timemixin.Label}
	default:
		return nil, &NotSingularError{timemixin.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (tmq *TimeMixinQuery) OnlyX(ctx context.Context) *TimeMixin {
	node, err := tmq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only TimeMixin ID in the query.
// Returns a *NotSingularError when exactly one TimeMixin ID is not found.
// Returns a *NotFoundError when no entities are found.
func (tmq *TimeMixinQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = tmq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{timemixin.Label}
	default:
		err = &NotSingularError{timemixin.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (tmq *TimeMixinQuery) OnlyIDX(ctx context.Context) int {
	id, err := tmq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of TimeMixins.
func (tmq *TimeMixinQuery) All(ctx context.Context) ([]*TimeMixin, error) {
	if err := tmq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return tmq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (tmq *TimeMixinQuery) AllX(ctx context.Context) []*TimeMixin {
	nodes, err := tmq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of TimeMixin IDs.
func (tmq *TimeMixinQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := tmq.Select(timemixin.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (tmq *TimeMixinQuery) IDsX(ctx context.Context) []int {
	ids, err := tmq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (tmq *TimeMixinQuery) Count(ctx context.Context) (int, error) {
	if err := tmq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return tmq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (tmq *TimeMixinQuery) CountX(ctx context.Context) int {
	count, err := tmq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (tmq *TimeMixinQuery) Exist(ctx context.Context) (bool, error) {
	if err := tmq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return tmq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (tmq *TimeMixinQuery) ExistX(ctx context.Context) bool {
	exist, err := tmq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the TimeMixinQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (tmq *TimeMixinQuery) Clone() *TimeMixinQuery {
	if tmq == nil {
		return nil
	}
	return &TimeMixinQuery{
		config:     tmq.config,
		limit:      tmq.limit,
		offset:     tmq.offset,
		order:      append([]OrderFunc{}, tmq.order...),
		predicates: append([]predicate.TimeMixin{}, tmq.predicates...),
		// clone intermediate query.
		sql:  tmq.sql.Clone(),
		path: tmq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.TimeMixin.Query().
//		GroupBy(timemixin.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (tmq *TimeMixinQuery) GroupBy(field string, fields ...string) *TimeMixinGroupBy {
	group := &TimeMixinGroupBy{config: tmq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := tmq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return tmq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.TimeMixin.Query().
//		Select(timemixin.FieldCreatedAt).
//		Scan(ctx, &v)
//
func (tmq *TimeMixinQuery) Select(fields ...string) *TimeMixinSelect {
	tmq.fields = append(tmq.fields, fields...)
	return &TimeMixinSelect{TimeMixinQuery: tmq}
}

func (tmq *TimeMixinQuery) prepareQuery(ctx context.Context) error {
	for _, f := range tmq.fields {
		if !timemixin.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if tmq.path != nil {
		prev, err := tmq.path(ctx)
		if err != nil {
			return err
		}
		tmq.sql = prev
	}
	return nil
}

func (tmq *TimeMixinQuery) sqlAll(ctx context.Context) ([]*TimeMixin, error) {
	var (
		nodes = []*TimeMixin{}
		_spec = tmq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &TimeMixin{config: tmq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, tmq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (tmq *TimeMixinQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := tmq.querySpec()
	return sqlgraph.CountNodes(ctx, tmq.driver, _spec)
}

func (tmq *TimeMixinQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := tmq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (tmq *TimeMixinQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   timemixin.Table,
			Columns: timemixin.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: timemixin.FieldID,
			},
		},
		From:   tmq.sql,
		Unique: true,
	}
	if unique := tmq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := tmq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, timemixin.FieldID)
		for i := range fields {
			if fields[i] != timemixin.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := tmq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := tmq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := tmq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := tmq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (tmq *TimeMixinQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(tmq.driver.Dialect())
	t1 := builder.Table(timemixin.Table)
	columns := tmq.fields
	if len(columns) == 0 {
		columns = timemixin.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if tmq.sql != nil {
		selector = tmq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	for _, p := range tmq.predicates {
		p(selector)
	}
	for _, p := range tmq.order {
		p(selector)
	}
	if offset := tmq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := tmq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// TimeMixinGroupBy is the group-by builder for TimeMixin entities.
type TimeMixinGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (tmgb *TimeMixinGroupBy) Aggregate(fns ...AggregateFunc) *TimeMixinGroupBy {
	tmgb.fns = append(tmgb.fns, fns...)
	return tmgb
}

// Scan applies the group-by query and scans the result into the given value.
func (tmgb *TimeMixinGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := tmgb.path(ctx)
	if err != nil {
		return err
	}
	tmgb.sql = query
	return tmgb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (tmgb *TimeMixinGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := tmgb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (tmgb *TimeMixinGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(tmgb.fields) > 1 {
		return nil, errors.New("ent: TimeMixinGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := tmgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (tmgb *TimeMixinGroupBy) StringsX(ctx context.Context) []string {
	v, err := tmgb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (tmgb *TimeMixinGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = tmgb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{timemixin.Label}
	default:
		err = fmt.Errorf("ent: TimeMixinGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (tmgb *TimeMixinGroupBy) StringX(ctx context.Context) string {
	v, err := tmgb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (tmgb *TimeMixinGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(tmgb.fields) > 1 {
		return nil, errors.New("ent: TimeMixinGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := tmgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (tmgb *TimeMixinGroupBy) IntsX(ctx context.Context) []int {
	v, err := tmgb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (tmgb *TimeMixinGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = tmgb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{timemixin.Label}
	default:
		err = fmt.Errorf("ent: TimeMixinGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (tmgb *TimeMixinGroupBy) IntX(ctx context.Context) int {
	v, err := tmgb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (tmgb *TimeMixinGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(tmgb.fields) > 1 {
		return nil, errors.New("ent: TimeMixinGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := tmgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (tmgb *TimeMixinGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := tmgb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (tmgb *TimeMixinGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = tmgb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{timemixin.Label}
	default:
		err = fmt.Errorf("ent: TimeMixinGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (tmgb *TimeMixinGroupBy) Float64X(ctx context.Context) float64 {
	v, err := tmgb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (tmgb *TimeMixinGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(tmgb.fields) > 1 {
		return nil, errors.New("ent: TimeMixinGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := tmgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (tmgb *TimeMixinGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := tmgb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (tmgb *TimeMixinGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = tmgb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{timemixin.Label}
	default:
		err = fmt.Errorf("ent: TimeMixinGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (tmgb *TimeMixinGroupBy) BoolX(ctx context.Context) bool {
	v, err := tmgb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (tmgb *TimeMixinGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range tmgb.fields {
		if !timemixin.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := tmgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tmgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (tmgb *TimeMixinGroupBy) sqlQuery() *sql.Selector {
	selector := tmgb.sql.Select()
	aggregation := make([]string, 0, len(tmgb.fns))
	for _, fn := range tmgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(tmgb.fields)+len(tmgb.fns))
		for _, f := range tmgb.fields {
			columns = append(columns, selector.C(f))
		}
		for _, c := range aggregation {
			columns = append(columns, c)
		}
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(tmgb.fields...)...)
}

// TimeMixinSelect is the builder for selecting fields of TimeMixin entities.
type TimeMixinSelect struct {
	*TimeMixinQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (tms *TimeMixinSelect) Scan(ctx context.Context, v interface{}) error {
	if err := tms.prepareQuery(ctx); err != nil {
		return err
	}
	tms.sql = tms.TimeMixinQuery.sqlQuery(ctx)
	return tms.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (tms *TimeMixinSelect) ScanX(ctx context.Context, v interface{}) {
	if err := tms.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (tms *TimeMixinSelect) Strings(ctx context.Context) ([]string, error) {
	if len(tms.fields) > 1 {
		return nil, errors.New("ent: TimeMixinSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := tms.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (tms *TimeMixinSelect) StringsX(ctx context.Context) []string {
	v, err := tms.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (tms *TimeMixinSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = tms.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{timemixin.Label}
	default:
		err = fmt.Errorf("ent: TimeMixinSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (tms *TimeMixinSelect) StringX(ctx context.Context) string {
	v, err := tms.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (tms *TimeMixinSelect) Ints(ctx context.Context) ([]int, error) {
	if len(tms.fields) > 1 {
		return nil, errors.New("ent: TimeMixinSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := tms.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (tms *TimeMixinSelect) IntsX(ctx context.Context) []int {
	v, err := tms.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (tms *TimeMixinSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = tms.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{timemixin.Label}
	default:
		err = fmt.Errorf("ent: TimeMixinSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (tms *TimeMixinSelect) IntX(ctx context.Context) int {
	v, err := tms.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (tms *TimeMixinSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(tms.fields) > 1 {
		return nil, errors.New("ent: TimeMixinSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := tms.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (tms *TimeMixinSelect) Float64sX(ctx context.Context) []float64 {
	v, err := tms.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (tms *TimeMixinSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = tms.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{timemixin.Label}
	default:
		err = fmt.Errorf("ent: TimeMixinSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (tms *TimeMixinSelect) Float64X(ctx context.Context) float64 {
	v, err := tms.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (tms *TimeMixinSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(tms.fields) > 1 {
		return nil, errors.New("ent: TimeMixinSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := tms.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (tms *TimeMixinSelect) BoolsX(ctx context.Context) []bool {
	v, err := tms.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (tms *TimeMixinSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = tms.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{timemixin.Label}
	default:
		err = fmt.Errorf("ent: TimeMixinSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (tms *TimeMixinSelect) BoolX(ctx context.Context) bool {
	v, err := tms.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (tms *TimeMixinSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := tms.sql.Query()
	if err := tms.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
