// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/msal4/hassah_school_server/ent/predicate"
	"github.com/msal4/hassah_school_server/ent/stage"
	"github.com/msal4/hassah_school_server/ent/tuitionpayment"
	"github.com/msal4/hassah_school_server/ent/user"
)

// TuitionPaymentQuery is the builder for querying TuitionPayment entities.
type TuitionPaymentQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.TuitionPayment
	// eager-loading edges.
	withStudent *UserQuery
	withStage   *StageQuery
	withFKs     bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the TuitionPaymentQuery builder.
func (tpq *TuitionPaymentQuery) Where(ps ...predicate.TuitionPayment) *TuitionPaymentQuery {
	tpq.predicates = append(tpq.predicates, ps...)
	return tpq
}

// Limit adds a limit step to the query.
func (tpq *TuitionPaymentQuery) Limit(limit int) *TuitionPaymentQuery {
	tpq.limit = &limit
	return tpq
}

// Offset adds an offset step to the query.
func (tpq *TuitionPaymentQuery) Offset(offset int) *TuitionPaymentQuery {
	tpq.offset = &offset
	return tpq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (tpq *TuitionPaymentQuery) Unique(unique bool) *TuitionPaymentQuery {
	tpq.unique = &unique
	return tpq
}

// Order adds an order step to the query.
func (tpq *TuitionPaymentQuery) Order(o ...OrderFunc) *TuitionPaymentQuery {
	tpq.order = append(tpq.order, o...)
	return tpq
}

// QueryStudent chains the current query on the "student" edge.
func (tpq *TuitionPaymentQuery) QueryStudent() *UserQuery {
	query := &UserQuery{config: tpq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := tpq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := tpq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(tuitionpayment.Table, tuitionpayment.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, tuitionpayment.StudentTable, tuitionpayment.StudentColumn),
		)
		fromU = sqlgraph.SetNeighbors(tpq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryStage chains the current query on the "stage" edge.
func (tpq *TuitionPaymentQuery) QueryStage() *StageQuery {
	query := &StageQuery{config: tpq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := tpq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := tpq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(tuitionpayment.Table, tuitionpayment.FieldID, selector),
			sqlgraph.To(stage.Table, stage.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, tuitionpayment.StageTable, tuitionpayment.StageColumn),
		)
		fromU = sqlgraph.SetNeighbors(tpq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first TuitionPayment entity from the query.
// Returns a *NotFoundError when no TuitionPayment was found.
func (tpq *TuitionPaymentQuery) First(ctx context.Context) (*TuitionPayment, error) {
	nodes, err := tpq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{tuitionpayment.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (tpq *TuitionPaymentQuery) FirstX(ctx context.Context) *TuitionPayment {
	node, err := tpq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first TuitionPayment ID from the query.
// Returns a *NotFoundError when no TuitionPayment ID was found.
func (tpq *TuitionPaymentQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = tpq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{tuitionpayment.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (tpq *TuitionPaymentQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := tpq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single TuitionPayment entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when exactly one TuitionPayment entity is not found.
// Returns a *NotFoundError when no TuitionPayment entities are found.
func (tpq *TuitionPaymentQuery) Only(ctx context.Context) (*TuitionPayment, error) {
	nodes, err := tpq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{tuitionpayment.Label}
	default:
		return nil, &NotSingularError{tuitionpayment.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (tpq *TuitionPaymentQuery) OnlyX(ctx context.Context) *TuitionPayment {
	node, err := tpq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only TuitionPayment ID in the query.
// Returns a *NotSingularError when exactly one TuitionPayment ID is not found.
// Returns a *NotFoundError when no entities are found.
func (tpq *TuitionPaymentQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = tpq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{tuitionpayment.Label}
	default:
		err = &NotSingularError{tuitionpayment.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (tpq *TuitionPaymentQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := tpq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of TuitionPayments.
func (tpq *TuitionPaymentQuery) All(ctx context.Context) ([]*TuitionPayment, error) {
	if err := tpq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return tpq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (tpq *TuitionPaymentQuery) AllX(ctx context.Context) []*TuitionPayment {
	nodes, err := tpq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of TuitionPayment IDs.
func (tpq *TuitionPaymentQuery) IDs(ctx context.Context) ([]uuid.UUID, error) {
	var ids []uuid.UUID
	if err := tpq.Select(tuitionpayment.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (tpq *TuitionPaymentQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := tpq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (tpq *TuitionPaymentQuery) Count(ctx context.Context) (int, error) {
	if err := tpq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return tpq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (tpq *TuitionPaymentQuery) CountX(ctx context.Context) int {
	count, err := tpq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (tpq *TuitionPaymentQuery) Exist(ctx context.Context) (bool, error) {
	if err := tpq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return tpq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (tpq *TuitionPaymentQuery) ExistX(ctx context.Context) bool {
	exist, err := tpq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the TuitionPaymentQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (tpq *TuitionPaymentQuery) Clone() *TuitionPaymentQuery {
	if tpq == nil {
		return nil
	}
	return &TuitionPaymentQuery{
		config:      tpq.config,
		limit:       tpq.limit,
		offset:      tpq.offset,
		order:       append([]OrderFunc{}, tpq.order...),
		predicates:  append([]predicate.TuitionPayment{}, tpq.predicates...),
		withStudent: tpq.withStudent.Clone(),
		withStage:   tpq.withStage.Clone(),
		// clone intermediate query.
		sql:  tpq.sql.Clone(),
		path: tpq.path,
	}
}

// WithStudent tells the query-builder to eager-load the nodes that are connected to
// the "student" edge. The optional arguments are used to configure the query builder of the edge.
func (tpq *TuitionPaymentQuery) WithStudent(opts ...func(*UserQuery)) *TuitionPaymentQuery {
	query := &UserQuery{config: tpq.config}
	for _, opt := range opts {
		opt(query)
	}
	tpq.withStudent = query
	return tpq
}

// WithStage tells the query-builder to eager-load the nodes that are connected to
// the "stage" edge. The optional arguments are used to configure the query builder of the edge.
func (tpq *TuitionPaymentQuery) WithStage(opts ...func(*StageQuery)) *TuitionPaymentQuery {
	query := &StageQuery{config: tpq.config}
	for _, opt := range opts {
		opt(query)
	}
	tpq.withStage = query
	return tpq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.TuitionPayment.Query().
//		GroupBy(tuitionpayment.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (tpq *TuitionPaymentQuery) GroupBy(field string, fields ...string) *TuitionPaymentGroupBy {
	group := &TuitionPaymentGroupBy{config: tpq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := tpq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return tpq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.TuitionPayment.Query().
//		Select(tuitionpayment.FieldCreatedAt).
//		Scan(ctx, &v)
//
func (tpq *TuitionPaymentQuery) Select(fields ...string) *TuitionPaymentSelect {
	tpq.fields = append(tpq.fields, fields...)
	return &TuitionPaymentSelect{TuitionPaymentQuery: tpq}
}

func (tpq *TuitionPaymentQuery) prepareQuery(ctx context.Context) error {
	for _, f := range tpq.fields {
		if !tuitionpayment.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if tpq.path != nil {
		prev, err := tpq.path(ctx)
		if err != nil {
			return err
		}
		tpq.sql = prev
	}
	return nil
}

func (tpq *TuitionPaymentQuery) sqlAll(ctx context.Context) ([]*TuitionPayment, error) {
	var (
		nodes       = []*TuitionPayment{}
		withFKs     = tpq.withFKs
		_spec       = tpq.querySpec()
		loadedTypes = [2]bool{
			tpq.withStudent != nil,
			tpq.withStage != nil,
		}
	)
	if tpq.withStudent != nil || tpq.withStage != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, tuitionpayment.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &TuitionPayment{config: tpq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, tpq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}

	if query := tpq.withStudent; query != nil {
		ids := make([]uuid.UUID, 0, len(nodes))
		nodeids := make(map[uuid.UUID][]*TuitionPayment)
		for i := range nodes {
			if nodes[i].user_payments == nil {
				continue
			}
			fk := *nodes[i].user_payments
			if _, ok := nodeids[fk]; !ok {
				ids = append(ids, fk)
			}
			nodeids[fk] = append(nodeids[fk], nodes[i])
		}
		query.Where(user.IDIn(ids...))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			nodes, ok := nodeids[n.ID]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "user_payments" returned %v`, n.ID)
			}
			for i := range nodes {
				nodes[i].Edges.Student = n
			}
		}
	}

	if query := tpq.withStage; query != nil {
		ids := make([]uuid.UUID, 0, len(nodes))
		nodeids := make(map[uuid.UUID][]*TuitionPayment)
		for i := range nodes {
			if nodes[i].stage_payments == nil {
				continue
			}
			fk := *nodes[i].stage_payments
			if _, ok := nodeids[fk]; !ok {
				ids = append(ids, fk)
			}
			nodeids[fk] = append(nodeids[fk], nodes[i])
		}
		query.Where(stage.IDIn(ids...))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			nodes, ok := nodeids[n.ID]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "stage_payments" returned %v`, n.ID)
			}
			for i := range nodes {
				nodes[i].Edges.Stage = n
			}
		}
	}

	return nodes, nil
}

func (tpq *TuitionPaymentQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := tpq.querySpec()
	return sqlgraph.CountNodes(ctx, tpq.driver, _spec)
}

func (tpq *TuitionPaymentQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := tpq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (tpq *TuitionPaymentQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   tuitionpayment.Table,
			Columns: tuitionpayment.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: tuitionpayment.FieldID,
			},
		},
		From:   tpq.sql,
		Unique: true,
	}
	if unique := tpq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := tpq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, tuitionpayment.FieldID)
		for i := range fields {
			if fields[i] != tuitionpayment.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := tpq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := tpq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := tpq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := tpq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (tpq *TuitionPaymentQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(tpq.driver.Dialect())
	t1 := builder.Table(tuitionpayment.Table)
	columns := tpq.fields
	if len(columns) == 0 {
		columns = tuitionpayment.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if tpq.sql != nil {
		selector = tpq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	for _, p := range tpq.predicates {
		p(selector)
	}
	for _, p := range tpq.order {
		p(selector)
	}
	if offset := tpq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := tpq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// TuitionPaymentGroupBy is the group-by builder for TuitionPayment entities.
type TuitionPaymentGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (tpgb *TuitionPaymentGroupBy) Aggregate(fns ...AggregateFunc) *TuitionPaymentGroupBy {
	tpgb.fns = append(tpgb.fns, fns...)
	return tpgb
}

// Scan applies the group-by query and scans the result into the given value.
func (tpgb *TuitionPaymentGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := tpgb.path(ctx)
	if err != nil {
		return err
	}
	tpgb.sql = query
	return tpgb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (tpgb *TuitionPaymentGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := tpgb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (tpgb *TuitionPaymentGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(tpgb.fields) > 1 {
		return nil, errors.New("ent: TuitionPaymentGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := tpgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (tpgb *TuitionPaymentGroupBy) StringsX(ctx context.Context) []string {
	v, err := tpgb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (tpgb *TuitionPaymentGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = tpgb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{tuitionpayment.Label}
	default:
		err = fmt.Errorf("ent: TuitionPaymentGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (tpgb *TuitionPaymentGroupBy) StringX(ctx context.Context) string {
	v, err := tpgb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (tpgb *TuitionPaymentGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(tpgb.fields) > 1 {
		return nil, errors.New("ent: TuitionPaymentGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := tpgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (tpgb *TuitionPaymentGroupBy) IntsX(ctx context.Context) []int {
	v, err := tpgb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (tpgb *TuitionPaymentGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = tpgb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{tuitionpayment.Label}
	default:
		err = fmt.Errorf("ent: TuitionPaymentGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (tpgb *TuitionPaymentGroupBy) IntX(ctx context.Context) int {
	v, err := tpgb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (tpgb *TuitionPaymentGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(tpgb.fields) > 1 {
		return nil, errors.New("ent: TuitionPaymentGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := tpgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (tpgb *TuitionPaymentGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := tpgb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (tpgb *TuitionPaymentGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = tpgb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{tuitionpayment.Label}
	default:
		err = fmt.Errorf("ent: TuitionPaymentGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (tpgb *TuitionPaymentGroupBy) Float64X(ctx context.Context) float64 {
	v, err := tpgb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (tpgb *TuitionPaymentGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(tpgb.fields) > 1 {
		return nil, errors.New("ent: TuitionPaymentGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := tpgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (tpgb *TuitionPaymentGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := tpgb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (tpgb *TuitionPaymentGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = tpgb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{tuitionpayment.Label}
	default:
		err = fmt.Errorf("ent: TuitionPaymentGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (tpgb *TuitionPaymentGroupBy) BoolX(ctx context.Context) bool {
	v, err := tpgb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (tpgb *TuitionPaymentGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range tpgb.fields {
		if !tuitionpayment.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := tpgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tpgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (tpgb *TuitionPaymentGroupBy) sqlQuery() *sql.Selector {
	selector := tpgb.sql.Select()
	aggregation := make([]string, 0, len(tpgb.fns))
	for _, fn := range tpgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(tpgb.fields)+len(tpgb.fns))
		for _, f := range tpgb.fields {
			columns = append(columns, selector.C(f))
		}
		for _, c := range aggregation {
			columns = append(columns, c)
		}
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(tpgb.fields...)...)
}

// TuitionPaymentSelect is the builder for selecting fields of TuitionPayment entities.
type TuitionPaymentSelect struct {
	*TuitionPaymentQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (tps *TuitionPaymentSelect) Scan(ctx context.Context, v interface{}) error {
	if err := tps.prepareQuery(ctx); err != nil {
		return err
	}
	tps.sql = tps.TuitionPaymentQuery.sqlQuery(ctx)
	return tps.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (tps *TuitionPaymentSelect) ScanX(ctx context.Context, v interface{}) {
	if err := tps.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (tps *TuitionPaymentSelect) Strings(ctx context.Context) ([]string, error) {
	if len(tps.fields) > 1 {
		return nil, errors.New("ent: TuitionPaymentSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := tps.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (tps *TuitionPaymentSelect) StringsX(ctx context.Context) []string {
	v, err := tps.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (tps *TuitionPaymentSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = tps.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{tuitionpayment.Label}
	default:
		err = fmt.Errorf("ent: TuitionPaymentSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (tps *TuitionPaymentSelect) StringX(ctx context.Context) string {
	v, err := tps.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (tps *TuitionPaymentSelect) Ints(ctx context.Context) ([]int, error) {
	if len(tps.fields) > 1 {
		return nil, errors.New("ent: TuitionPaymentSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := tps.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (tps *TuitionPaymentSelect) IntsX(ctx context.Context) []int {
	v, err := tps.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (tps *TuitionPaymentSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = tps.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{tuitionpayment.Label}
	default:
		err = fmt.Errorf("ent: TuitionPaymentSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (tps *TuitionPaymentSelect) IntX(ctx context.Context) int {
	v, err := tps.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (tps *TuitionPaymentSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(tps.fields) > 1 {
		return nil, errors.New("ent: TuitionPaymentSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := tps.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (tps *TuitionPaymentSelect) Float64sX(ctx context.Context) []float64 {
	v, err := tps.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (tps *TuitionPaymentSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = tps.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{tuitionpayment.Label}
	default:
		err = fmt.Errorf("ent: TuitionPaymentSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (tps *TuitionPaymentSelect) Float64X(ctx context.Context) float64 {
	v, err := tps.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (tps *TuitionPaymentSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(tps.fields) > 1 {
		return nil, errors.New("ent: TuitionPaymentSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := tps.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (tps *TuitionPaymentSelect) BoolsX(ctx context.Context) []bool {
	v, err := tps.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (tps *TuitionPaymentSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = tps.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{tuitionpayment.Label}
	default:
		err = fmt.Errorf("ent: TuitionPaymentSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (tps *TuitionPaymentSelect) BoolX(ctx context.Context) bool {
	v, err := tps.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (tps *TuitionPaymentSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := tps.sql.Query()
	if err := tps.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
