// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/msal4/hassah_school_server/ent/predicate"
	"github.com/msal4/hassah_school_server/ent/stage"
	"github.com/msal4/hassah_school_server/ent/tuitionpayment"
	"github.com/msal4/hassah_school_server/ent/user"
)

// TuitionPaymentUpdate is the builder for updating TuitionPayment entities.
type TuitionPaymentUpdate struct {
	config
	hooks    []Hook
	mutation *TuitionPaymentMutation
}

// Where appends a list predicates to the TuitionPaymentUpdate builder.
func (tpu *TuitionPaymentUpdate) Where(ps ...predicate.TuitionPayment) *TuitionPaymentUpdate {
	tpu.mutation.Where(ps...)
	return tpu
}

// SetPaidAmount sets the "paid_amount" field.
func (tpu *TuitionPaymentUpdate) SetPaidAmount(i int) *TuitionPaymentUpdate {
	tpu.mutation.ResetPaidAmount()
	tpu.mutation.SetPaidAmount(i)
	return tpu
}

// AddPaidAmount adds i to the "paid_amount" field.
func (tpu *TuitionPaymentUpdate) AddPaidAmount(i int) *TuitionPaymentUpdate {
	tpu.mutation.AddPaidAmount(i)
	return tpu
}

// SetStudentID sets the "student" edge to the User entity by ID.
func (tpu *TuitionPaymentUpdate) SetStudentID(id int) *TuitionPaymentUpdate {
	tpu.mutation.SetStudentID(id)
	return tpu
}

// SetStudent sets the "student" edge to the User entity.
func (tpu *TuitionPaymentUpdate) SetStudent(u *User) *TuitionPaymentUpdate {
	return tpu.SetStudentID(u.ID)
}

// SetStageID sets the "stage" edge to the Stage entity by ID.
func (tpu *TuitionPaymentUpdate) SetStageID(id int) *TuitionPaymentUpdate {
	tpu.mutation.SetStageID(id)
	return tpu
}

// SetStage sets the "stage" edge to the Stage entity.
func (tpu *TuitionPaymentUpdate) SetStage(s *Stage) *TuitionPaymentUpdate {
	return tpu.SetStageID(s.ID)
}

// Mutation returns the TuitionPaymentMutation object of the builder.
func (tpu *TuitionPaymentUpdate) Mutation() *TuitionPaymentMutation {
	return tpu.mutation
}

// ClearStudent clears the "student" edge to the User entity.
func (tpu *TuitionPaymentUpdate) ClearStudent() *TuitionPaymentUpdate {
	tpu.mutation.ClearStudent()
	return tpu
}

// ClearStage clears the "stage" edge to the Stage entity.
func (tpu *TuitionPaymentUpdate) ClearStage() *TuitionPaymentUpdate {
	tpu.mutation.ClearStage()
	return tpu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (tpu *TuitionPaymentUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	tpu.defaults()
	if len(tpu.hooks) == 0 {
		if err = tpu.check(); err != nil {
			return 0, err
		}
		affected, err = tpu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*TuitionPaymentMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = tpu.check(); err != nil {
				return 0, err
			}
			tpu.mutation = mutation
			affected, err = tpu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(tpu.hooks) - 1; i >= 0; i-- {
			if tpu.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = tpu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, tpu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (tpu *TuitionPaymentUpdate) SaveX(ctx context.Context) int {
	affected, err := tpu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (tpu *TuitionPaymentUpdate) Exec(ctx context.Context) error {
	_, err := tpu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tpu *TuitionPaymentUpdate) ExecX(ctx context.Context) {
	if err := tpu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (tpu *TuitionPaymentUpdate) defaults() {
	if _, ok := tpu.mutation.UpdateTime(); !ok {
		v := tuitionpayment.UpdateDefaultUpdateTime()
		tpu.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tpu *TuitionPaymentUpdate) check() error {
	if _, ok := tpu.mutation.StudentID(); tpu.mutation.StudentCleared() && !ok {
		return errors.New("ent: clearing a required unique edge \"student\"")
	}
	if _, ok := tpu.mutation.StageID(); tpu.mutation.StageCleared() && !ok {
		return errors.New("ent: clearing a required unique edge \"stage\"")
	}
	return nil
}

func (tpu *TuitionPaymentUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   tuitionpayment.Table,
			Columns: tuitionpayment.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: tuitionpayment.FieldID,
			},
		},
	}
	if ps := tpu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tpu.mutation.UpdateTime(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: tuitionpayment.FieldUpdateTime,
		})
	}
	if value, ok := tpu.mutation.PaidAmount(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: tuitionpayment.FieldPaidAmount,
		})
	}
	if value, ok := tpu.mutation.AddedPaidAmount(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: tuitionpayment.FieldPaidAmount,
		})
	}
	if tpu.mutation.StudentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tuitionpayment.StudentTable,
			Columns: []string{tuitionpayment.StudentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tpu.mutation.StudentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tuitionpayment.StudentTable,
			Columns: []string{tuitionpayment.StudentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if tpu.mutation.StageCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tuitionpayment.StageTable,
			Columns: []string{tuitionpayment.StageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: stage.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tpu.mutation.StageIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tuitionpayment.StageTable,
			Columns: []string{tuitionpayment.StageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: stage.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, tpu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tuitionpayment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return 0, err
	}
	return n, nil
}

// TuitionPaymentUpdateOne is the builder for updating a single TuitionPayment entity.
type TuitionPaymentUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TuitionPaymentMutation
}

// SetPaidAmount sets the "paid_amount" field.
func (tpuo *TuitionPaymentUpdateOne) SetPaidAmount(i int) *TuitionPaymentUpdateOne {
	tpuo.mutation.ResetPaidAmount()
	tpuo.mutation.SetPaidAmount(i)
	return tpuo
}

// AddPaidAmount adds i to the "paid_amount" field.
func (tpuo *TuitionPaymentUpdateOne) AddPaidAmount(i int) *TuitionPaymentUpdateOne {
	tpuo.mutation.AddPaidAmount(i)
	return tpuo
}

// SetStudentID sets the "student" edge to the User entity by ID.
func (tpuo *TuitionPaymentUpdateOne) SetStudentID(id int) *TuitionPaymentUpdateOne {
	tpuo.mutation.SetStudentID(id)
	return tpuo
}

// SetStudent sets the "student" edge to the User entity.
func (tpuo *TuitionPaymentUpdateOne) SetStudent(u *User) *TuitionPaymentUpdateOne {
	return tpuo.SetStudentID(u.ID)
}

// SetStageID sets the "stage" edge to the Stage entity by ID.
func (tpuo *TuitionPaymentUpdateOne) SetStageID(id int) *TuitionPaymentUpdateOne {
	tpuo.mutation.SetStageID(id)
	return tpuo
}

// SetStage sets the "stage" edge to the Stage entity.
func (tpuo *TuitionPaymentUpdateOne) SetStage(s *Stage) *TuitionPaymentUpdateOne {
	return tpuo.SetStageID(s.ID)
}

// Mutation returns the TuitionPaymentMutation object of the builder.
func (tpuo *TuitionPaymentUpdateOne) Mutation() *TuitionPaymentMutation {
	return tpuo.mutation
}

// ClearStudent clears the "student" edge to the User entity.
func (tpuo *TuitionPaymentUpdateOne) ClearStudent() *TuitionPaymentUpdateOne {
	tpuo.mutation.ClearStudent()
	return tpuo
}

// ClearStage clears the "stage" edge to the Stage entity.
func (tpuo *TuitionPaymentUpdateOne) ClearStage() *TuitionPaymentUpdateOne {
	tpuo.mutation.ClearStage()
	return tpuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (tpuo *TuitionPaymentUpdateOne) Select(field string, fields ...string) *TuitionPaymentUpdateOne {
	tpuo.fields = append([]string{field}, fields...)
	return tpuo
}

// Save executes the query and returns the updated TuitionPayment entity.
func (tpuo *TuitionPaymentUpdateOne) Save(ctx context.Context) (*TuitionPayment, error) {
	var (
		err  error
		node *TuitionPayment
	)
	tpuo.defaults()
	if len(tpuo.hooks) == 0 {
		if err = tpuo.check(); err != nil {
			return nil, err
		}
		node, err = tpuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*TuitionPaymentMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = tpuo.check(); err != nil {
				return nil, err
			}
			tpuo.mutation = mutation
			node, err = tpuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(tpuo.hooks) - 1; i >= 0; i-- {
			if tpuo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = tpuo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, tpuo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (tpuo *TuitionPaymentUpdateOne) SaveX(ctx context.Context) *TuitionPayment {
	node, err := tpuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (tpuo *TuitionPaymentUpdateOne) Exec(ctx context.Context) error {
	_, err := tpuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tpuo *TuitionPaymentUpdateOne) ExecX(ctx context.Context) {
	if err := tpuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (tpuo *TuitionPaymentUpdateOne) defaults() {
	if _, ok := tpuo.mutation.UpdateTime(); !ok {
		v := tuitionpayment.UpdateDefaultUpdateTime()
		tpuo.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tpuo *TuitionPaymentUpdateOne) check() error {
	if _, ok := tpuo.mutation.StudentID(); tpuo.mutation.StudentCleared() && !ok {
		return errors.New("ent: clearing a required unique edge \"student\"")
	}
	if _, ok := tpuo.mutation.StageID(); tpuo.mutation.StageCleared() && !ok {
		return errors.New("ent: clearing a required unique edge \"stage\"")
	}
	return nil
}

func (tpuo *TuitionPaymentUpdateOne) sqlSave(ctx context.Context) (_node *TuitionPayment, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   tuitionpayment.Table,
			Columns: tuitionpayment.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: tuitionpayment.FieldID,
			},
		},
	}
	id, ok := tpuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing TuitionPayment.ID for update")}
	}
	_spec.Node.ID.Value = id
	if fields := tpuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, tuitionpayment.FieldID)
		for _, f := range fields {
			if !tuitionpayment.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != tuitionpayment.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := tpuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tpuo.mutation.UpdateTime(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: tuitionpayment.FieldUpdateTime,
		})
	}
	if value, ok := tpuo.mutation.PaidAmount(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: tuitionpayment.FieldPaidAmount,
		})
	}
	if value, ok := tpuo.mutation.AddedPaidAmount(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: tuitionpayment.FieldPaidAmount,
		})
	}
	if tpuo.mutation.StudentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tuitionpayment.StudentTable,
			Columns: []string{tuitionpayment.StudentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tpuo.mutation.StudentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tuitionpayment.StudentTable,
			Columns: []string{tuitionpayment.StudentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if tpuo.mutation.StageCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tuitionpayment.StageTable,
			Columns: []string{tuitionpayment.StageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: stage.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tpuo.mutation.StageIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tuitionpayment.StageTable,
			Columns: []string{tuitionpayment.StageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: stage.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &TuitionPayment{config: tpuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, tpuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tuitionpayment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	return _node, nil
}
