name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      minio:
        image: bitnami/minio:latest
        env:
          MINIO_ROOT_USER: minio
          MINIO_ROOT_PASSWORD: minio
        ports:
        - 9000:9000
        options: >-
          --health-cmd "curl -f http://localhost:9000/minio/health/live"
          --health-retries 5
          --health-interval 30s
          --health-timeout 20s

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    
    - name: Build
      run: go build -v ./...
    - name: Test
      run: make test
    env:
      MINIO_ENDPOINT: 127.0.0.1:9000
      MINIO_ACCESS_KEY: minio
      MINIO_TOKEN: minio
