name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      minio:
        image: minio/minio
        env:
          MINIO_ROOT_USER: minio
          MINIO_ROOT_PASSWORD: minio
        ports: 
          - 9000:9000
        options: >-
          --health-cmd "curl http://localhost:9000/minio/health/live"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    
    - name: Build
      run: go build -v ./...
    - name: Wait for minio to start
      run: "curl https://raw.githubusercontent.com/harshavardhana/minio-kafka/master/wait-for.sh -o wait-for.sh; chmod +x wait-for.sh; ./wait-for.sh localhost:9000"
    - name: Test
      run: make test
    env:
      MINIO_ENDPOINT: 127.0.0.1:9000
      MINIO_ACCESS_KEY: minio
      MINIO_TOKEN: minio
