name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      minio:
        image: lazybit/minio
        # does not apply since the image does not recognize these vars.
        env:
          MINIO_ROOT_USER: minio 
          MINIO_ROOT_PASSWORD: minio
        ports:
        - 9000:9000

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    
    - name: Build
      run: go build -v ./...
    - name: Test
      run: make test
    env:
      MINIO_ENDPOINT: 127.0.0.1:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_TOKEN: minioadmin
